name: opensim-torque
channels:
  - opensim-org
  - conda-forge
  - pytorch
dependencies:
  - python=3.11
  - opensim=4.5.2
  - numpy<2
  - scipy>=1.10,<1.14
  - pyyaml
  - trimesh
  - rtree
  - tqdm
  - pandas
  - matplotlib
  - pytorch
  - pip
  - pip:
      - smplx
      - nimblephysics
      - meshio
