from __future__ import annotations

import json
import os
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class AddBiomechanicsRunResult:
    """Paths generated by a local AddBiomechanics engine run."""

    addbio_root: Path
    engine_src_dir: Path
    subject_root: Path
    output_name: str
    output_root: Path
    final_model_path: Path
    final_mot_path: Path
    errors_path: Path
    stdout: str
    stderr: str


def resolve_addbio_root(addbio_root: str | Path | None = None) -> Path:
    """Resolve the AddBiomechanics checkout from an argument or environment."""
    candidate = addbio_root or os.environ.get("ADDBIO_ENGINE_ROOT")
    if not candidate:
        raise ValueError(
            "AddBiomechanics root is required. Pass --addbio-root or set ADDBIO_ENGINE_ROOT."
        )

    root = Path(candidate).expanduser().resolve()
    engine_src = root / "server" / "engine" / "src"
    engine_py = engine_src / "engine.py"
    if not engine_py.exists():
        raise FileNotFoundError(f"Could not find AddBiomechanics engine.py at {engine_py}")
    return root


def _merge_segment_mots(segment_paths: list[Path], output_path: Path) -> Path:
    """Merge AddBiomechanics segment MOTs when no combined MOT was emitted."""
    if not segment_paths:
        raise FileNotFoundError("No AddBiomechanics IK segment files found.")
    first = segment_paths[0].read_text(encoding="utf-8")
    marker = "endheader"
    if marker not in first:
        raise ValueError(f"Invalid MOT header: {segment_paths[0]}")
    header, first_data = first.split(marker, 1)
    data_sections = [first_data.strip().splitlines()]
    for path in segment_paths[1:]:
        text = path.read_text(encoding="utf-8")
        if marker not in text:
            raise ValueError(f"Invalid MOT header: {path}")
        _, data = text.split(marker, 1)
        lines = data.strip().splitlines()
        data_sections.append(lines)
    labels = data_sections[0][0]
    rows: list[str] = []
    for section in data_sections:
        if not section or section[0] != labels:
            raise ValueError(f"MOT segment labels do not match: {segment_paths[0]}")
        rows.extend(section[1:])
    header_lines = header.splitlines()
    header_lines = [
        line for line in header_lines
        if not line.startswith("datarows ") and not line.startswith("range ")
    ]
    times = [float(row.split()[0]) for row in rows]
    header_lines.extend((f"datarows {len(rows)}", f"range {times[0]:.8f} {times[-1]:.8f}"))
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        "\n".join(header_lines + [marker, labels, *rows]) + "\n",
        encoding="utf-8",
    )
    return output_path


def run_addbiomechanics_engine(
    subject_root: str | Path,
    addbio_root: str | Path | None = None,
    output_name: str = "results",
    href: str = "",
) -> AddBiomechanicsRunResult:
    """Run the local AddBiomechanics engine over a prepared subject folder."""
    root = resolve_addbio_root(addbio_root)
    engine_src = root / "server" / "engine" / "src"
    subject_root = Path(subject_root).resolve()
    errors_path = subject_root / "_errors.json"
    if errors_path.exists():
        errors_path.unlink()

    command = [
        sys.executable,
        "engine.py",
        str(subject_root),
        output_name,
        href,
    ]
    run_env = {**os.environ}
    # On macOS this avoids hard failures when multiple OpenMP runtimes are loaded.
    run_env.setdefault("KMP_DUPLICATE_LIB_OK", "TRUE")
    # Ensure subprocesses spawned by AddBiomechanics (opensim-cmd, etc.) resolve from
    # the same Python environment used to launch this runner.
    python_bin_dir = str(Path(sys.executable).resolve().parent)
    existing_path = run_env.get("PATH", "")
    run_env["PATH"] = (
        f"{python_bin_dir}{os.pathsep}{existing_path}" if existing_path else python_bin_dir
    )

    result = subprocess.run(
        command,
        cwd=engine_src,
        capture_output=True,
        text=True,
        env=run_env,
    )

    output_root = subject_root / output_name
    final_model_path = output_root / "Models" / "match_markers_but_ignore_physics.osim"
    ik_dir = output_root / "IK"
    final_mot_path = ik_dir / f"{subject_root.name}_ik.mot"

    if errors_path.exists():
        raise RuntimeError(
            "AddBiomechanics engine wrote an error JSON.\n"
            f"Subject folder: {subject_root}\n"
            f"Error file: {errors_path}\n"
            f"stdout:\n{result.stdout}\n"
            f"stderr:\n{result.stderr}"
        )

    if result.returncode != 0:
        raise RuntimeError(
            "AddBiomechanics engine failed.\n"
            f"Command: {' '.join(command)}\n"
            f"stdout:\n{result.stdout}\n"
            f"stderr:\n{result.stderr}"
        )

    if not final_model_path.exists():
        raise FileNotFoundError(f"Missing final model output: {final_model_path}")
    if not final_mot_path.exists():
        segment_candidates = sorted(ik_dir.glob(f"{subject_root.name}_segment_*_ik.mot"))
        if segment_candidates:
            final_mot_path = _merge_segment_mots(
                segment_candidates,
                ik_dir / f"{subject_root.name}_ik.mot",
            )
        else:
            any_candidate = sorted(ik_dir.glob("*_ik.mot"))
            if any_candidate:
                final_mot_path = any_candidate[0]
            else:
                raise FileNotFoundError(f"Missing final IK motion output: {final_mot_path}")

    return AddBiomechanicsRunResult(
        addbio_root=root,
        engine_src_dir=engine_src,
        subject_root=subject_root,
        output_name=output_name,
        output_root=output_root,
        final_model_path=final_model_path,
        final_mot_path=final_mot_path,
        errors_path=errors_path,
        stdout=result.stdout,
        stderr=result.stderr,
    )


def _json_default(value: object) -> object:
    if isinstance(value, Path):
        return str(value)
    raise TypeError(f"Object of type {type(value).__name__} is not JSON serializable")


def result_to_json(result: AddBiomechanicsRunResult) -> str:
    """Serialize the run result as a stable JSON blob."""
    return json.dumps(result.__dict__, indent=2, default=_json_default)
