from __future__ import annotations

import csv
import math
import os
import shutil
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

import numpy as np

from .mot_to_csv import (
    extract_coordinate_names_from_osim,
    infer_cutoff_hz,
    parse_mot,
)


@dataclass(frozen=True)
class InverseDynamicsNoGrfSummary:
    """Artifacts generated by inverse dynamics without explicit GRF input."""

    model_path: Path
    ik_mot_path: Path
    id_setup_path: Path
    id_sto_path: Path
    torque_csv_path: Path
    dof_names: tuple[str, ...]
    frames: int
    cutoff_hz: float | None
    missing_dofs: tuple[str, ...]
    grf_mode: str
    grf_mot_path: Path | None = None
    external_loads_xml_path: Path | None = None
    contact_wrench_csv_path: Path | None = None


def _canonical_label(label: str) -> str:
    label = label.strip()
    if "/" not in label:
        return label
    parts = [part for part in label.split("/") if part]
    if not parts:
        return label
    if parts[-1].lower() == "value" and len(parts) >= 2:
        return parts[-2]
    return parts[-1]


def _find_opensim_cmd() -> str | None:
    """Resolve opensim-cmd from PATH or the active Python environment."""
    candidates: list[Path] = []

    resolved_from_path = shutil.which("opensim-cmd")
    if resolved_from_path:
        candidates.append(Path(resolved_from_path))

    env_prefix = os.environ.get("CONDA_PREFIX")
    if env_prefix:
        candidates.append(Path(env_prefix) / "bin" / "opensim-cmd")

    candidates.append(Path(sys.prefix) / "bin" / "opensim-cmd")
    candidates.append(Path(sys.exec_prefix) / "bin" / "opensim-cmd")

    seen: set[str] = set()
    for candidate in candidates:
        key = str(candidate)
        if key in seen:
            continue
        seen.add(key)
        if candidate.exists():
            return str(candidate)
    return None


def _run_opensim_tool(setup_xml: Path) -> None:
    opensim_cmd = _find_opensim_cmd()
    if opensim_cmd:
        command = [opensim_cmd, "-o", "error", "run-tool", str(setup_xml)]
        result = subprocess.run(command, capture_output=True, text=True)
        if result.returncode != 0:
            raise RuntimeError(
                "OpenSim inverse dynamics failed.\n"
                f"Command: {' '.join(command)}\n"
                f"stdout:\n{result.stdout}\n"
                f"stderr:\n{result.stderr}"
            )
        return

    try:
        import opensim
    except ImportError as exc:
        raise RuntimeError(
            "Could not run inverse dynamics: opensim-cmd was not found and the "
            "opensim Python package is unavailable."
        ) from exc

    tool = opensim.InverseDynamicsTool(str(setup_xml))
    success = tool.run()
    if success is False:
        raise RuntimeError(
            "OpenSim inverse dynamics failed while running through the Python API."
        )


def _prepare_model_for_inverse_dynamics(
    model_path: Path,
    output_dir: Path,
    trial_name: str,
) -> Path:
    """
    Create a marker-free model copy for inverse dynamics.

    ID does not use markers, and stripping them avoids socket-resolution issues
    in models exported by AddBiomechanics/OpenCap conversions.
    """
    try:
        import opensim
    except ImportError as exc:
        raise RuntimeError(
            "opensim Python package is required to prepare the model for inverse dynamics."
        ) from exc

    prepared_model_path = output_dir / f"{trial_name}_id_model_nomarkers.osim"
    opensim.Logger.setLevelString("error")
    model = opensim.Model(str(model_path))
    marker_set = model.updMarkerSet()
    if marker_set.getSize() > 0:
        marker_set.clearAndDestroy()
        model.finalizeConnections()
    model.printToXML(str(prepared_model_path))
    return prepared_model_path


def _project_point_to_plane(point: np.ndarray, up: np.ndarray, plane_offset: float) -> np.ndarray:
    """Project a 3D point to the plane {x | dot(x, up) = plane_offset}."""
    return point - (float(np.dot(point, up)) - plane_offset) * up


def _lowpass_butterworth_4th(
    values: np.ndarray,
    sample_rate_hz: float,
    cutoff_hz: float | None,
) -> np.ndarray:
    """
    Apply a 4th-order zero-phase Butterworth low-pass filter.

    If filtering is unavailable or not meaningful for the signal length, this
    function returns a copy of the input.
    """
    if cutoff_hz is None:
        return values.copy()
    if values.size < 20:
        return values.copy()

    try:
        from scipy.signal import butter, filtfilt
    except ImportError:
        return values.copy()

    nyquist_hz = 0.5 * float(sample_rate_hz)
    effective_cutoff = min(float(cutoff_hz), 0.95 * nyquist_hz)
    if effective_cutoff <= 0.0:
        return values.copy()
    b, a = butter(4, effective_cutoff, btype="low", fs=float(sample_rate_hz))
    return filtfilt(b, a, values)


def _project_force_to_friction_cone(
    force: np.ndarray,
    up: np.ndarray,
    friction_coeff: float,
) -> np.ndarray:
    """Project a force onto a linearized Coulomb friction cone with normal +up."""
    normal_force = float(np.dot(force, up))
    normal_force = max(0.0, normal_force)
    tangential = force - normal_force * up
    tangential_norm = float(np.linalg.norm(tangential))
    tangential_limit = float(friction_coeff) * normal_force
    if tangential_norm > tangential_limit > 0.0:
        tangential = tangential * (tangential_limit / tangential_norm)
    return tangential + normal_force * up


def _estimate_contact_wrenches_from_kinematics(
    model_path: Path,
    ik_mot_path: Path,
    output_dir: Path,
    trial_name: str,
    contact_body_names: tuple[str, ...],
    friction_coeff: float,
    contact_height_threshold_m: float,
    contact_speed_threshold_mps: float,
    force_cutoff_hz: float | None,
) -> tuple[Path, Path, Path]:
    """
    Estimate multi-body contact wrenches from kinematics and export OpenSim GRF artifacts.

    This implementation enforces linear COM dynamics:
        sum(F_contacts) ~= m * (a_com - g)
    and distributes the force over active contact bodies with geometric heuristics.
    """
    try:
        import nimblephysics as nimble
    except ImportError as exc:
        raise RuntimeError(
            "nimblephysics is required to estimate GRF/contact wrenches from kinematics."
        ) from exc

    output_dir.mkdir(parents=True, exist_ok=True)
    grf_mot_path = output_dir / f"{trial_name}_grf_estimated.mot"
    external_loads_xml_path = output_dir / f"{trial_name}_external_forces_estimated.xml"
    contact_wrench_csv_path = output_dir / f"{trial_name}_contact_wrenches_estimated.csv"

    osim = nimble.biomechanics.OpenSimParser.parseOsim(str(model_path), "", True)
    skel = osim.skeleton
    mot = nimble.biomechanics.OpenSimParser.loadMot(skel, str(ik_mot_path))
    poses = np.asarray(mot.poses, dtype=np.float64)
    timestamps = np.asarray(mot.timestamps, dtype=np.float64)
    if poses.ndim != 2 or poses.shape[1] < 5:
        raise ValueError("IK motion does not contain enough frames for GRF estimation.")
    if timestamps.size != poses.shape[1]:
        raise ValueError("Mismatch between IK timestamps and pose samples.")
    dt = np.diff(timestamps)
    finite_dt = dt[np.isfinite(dt)]
    finite_dt = finite_dt[finite_dt > 0.0]
    if finite_dt.size == 0:
        raise ValueError("Could not infer sample rate from IK timestamps.")
    sample_rate_hz = 1.0 / float(np.median(finite_dt))

    gravity = np.asarray(skel.getGravity(), dtype=np.float64).reshape(3)
    gravity_norm = float(np.linalg.norm(gravity))
    if gravity_norm < 1e-8:
        raise ValueError("Model gravity magnitude is near zero; cannot estimate GRFs.")
    up = -gravity / gravity_norm
    mass_kg = float(skel.getMass())

    available_names = [skel.getBodyNode(i).getName() for i in range(skel.getNumBodyNodes())]
    available_set = set(available_names)

    requested_names = tuple(name.strip() for name in contact_body_names if name.strip())
    requested_lower = {name.lower() for name in requested_names}
    use_all_bodies = bool(requested_lower & {"all", "auto", "*"})

    if use_all_bodies:
        selected_names = [name for name in available_names if name.lower() != "ground"]
    else:
        selected_names = [name for name in requested_names if name in available_set]

    if not selected_names:
        for fallback in (
            "toes_l",
            "toes_r",
            "foot_l",
            "foot_r",
            "calcn_l",
            "calcn_r",
            "hand_l",
            "hand_r",
        ):
            if fallback in available_set and fallback not in selected_names:
                selected_names.append(fallback)
    if not selected_names and available_names:
        # Last-resort fallback: keep pipeline runnable on unfamiliar models.
        selected_names = [available_names[0]]
    if not selected_names:
        raise ValueError(
            "Could not resolve any contact body for GRF estimation. "
            f"Requested={contact_body_names}, available={available_names}"
        )
    contact_nodes = [skel.getBodyNode(name) for name in selected_names]

    frames = poses.shape[1]
    com_positions = np.zeros((frames, 3), dtype=np.float64)
    body_positions = np.zeros((len(contact_nodes), frames, 3), dtype=np.float64)
    for frame_idx in range(frames):
        skel.setPositions(poses[:, frame_idx])
        com_positions[frame_idx, :] = np.asarray(skel.getCOM(), dtype=np.float64).reshape(3)
        for body_idx, body in enumerate(contact_nodes):
            body_positions[body_idx, frame_idx, :] = np.asarray(
                body.getWorldTransform().translation(), dtype=np.float64
            ).reshape(3)

    com_positions_filt = np.zeros_like(com_positions)
    for axis in range(3):
        com_positions_filt[:, axis] = _lowpass_butterworth_4th(
            com_positions[:, axis],
            sample_rate_hz=sample_rate_hz,
            cutoff_hz=force_cutoff_hz,
        )
    body_positions_filt = np.zeros_like(body_positions)
    for body_idx in range(len(contact_nodes)):
        for axis in range(3):
            body_positions_filt[body_idx, :, axis] = _lowpass_butterworth_4th(
                body_positions[body_idx, :, axis],
                sample_rate_hz=sample_rate_hz,
                cutoff_hz=force_cutoff_hz,
            )

    # Use a robust estimate of floor height from contact body trajectories.
    heights_all = body_positions_filt @ up
    ground_height = float(np.percentile(heights_all, 1.0))

    com_acc = np.gradient(
        np.gradient(com_positions_filt, timestamps, axis=0),
        timestamps,
        axis=0,
    )
    total_external_force = mass_kg * (com_acc - gravity.reshape(1, 3))
    for axis in range(3):
        total_external_force[:, axis] = _lowpass_butterworth_4th(
            total_external_force[:, axis],
            sample_rate_hz=sample_rate_hz,
            cutoff_hz=force_cutoff_hz,
        )

    window_frames = max(1, int(round(0.04 / float(np.median(np.diff(timestamps))))))
    kernel = np.ones((2 * window_frames + 1,), dtype=np.int32)

    force_per_body = np.zeros((len(contact_nodes), frames, 3), dtype=np.float64)
    cop_per_body = np.zeros((len(contact_nodes), frames, 3), dtype=np.float64)
    torque_per_body = np.zeros((len(contact_nodes), frames, 3), dtype=np.float64)

    for body_idx in range(len(contact_nodes)):
        for frame_idx in range(frames):
            point = body_positions_filt[body_idx, frame_idx, :]
            cop_per_body[body_idx, frame_idx, :] = _project_point_to_plane(point, up, ground_height)

    height_per_body = heights_all - ground_height
    normal_speed_per_body = np.gradient(heights_all, timestamps, axis=1)
    active_mask = (height_per_body <= contact_height_threshold_m) & (
        np.abs(normal_speed_per_body) <= contact_speed_threshold_mps
    )
    # Briefly close gaps to avoid frame-by-frame force flicker.
    for body_idx in range(active_mask.shape[0]):
        expanded = np.convolve(active_mask[body_idx, :].astype(np.int32), kernel, mode="same") > 0
        active_mask[body_idx, :] = expanded

    for frame_idx in range(frames):
        force_target = total_external_force[frame_idx, :].copy()
        up_component = float(np.dot(force_target, up))
        if up_component <= 0.0:
            # Airborne/no support: keep zero contact forces.
            continue

        active_indices = [i for i in range(len(contact_nodes)) if active_mask[i, frame_idx]]
        if not active_indices:
            # Fallback: use closest body to floor if no active contact was detected.
            min_idx = int(np.argmin(height_per_body[:, frame_idx]))
            active_indices = [min_idx]

        com_proj = _project_point_to_plane(com_positions_filt[frame_idx, :], up, ground_height)
        weights = np.zeros((len(contact_nodes),), dtype=np.float64)
        for i in active_indices:
            point = cop_per_body[i, frame_idx, :]
            planar_delta = point - com_proj
            planar_delta -= float(np.dot(planar_delta, up)) * up
            distance = float(np.linalg.norm(planar_delta))
            weights[i] = 1.0 / (distance + 1e-3)
        weight_sum = float(np.sum(weights))
        if weight_sum <= 1e-12:
            for i in active_indices:
                weights[i] = 1.0
            weight_sum = float(np.sum(weights))
        weights /= weight_sum

        for body_idx in range(len(contact_nodes)):
            if weights[body_idx] <= 0.0:
                continue
            force = weights[body_idx] * force_target
            force_per_body[body_idx, frame_idx, :] = _project_force_to_friction_cone(
                force=force,
                up=up,
                friction_coeff=friction_coeff,
            )

        # Project-distribute iterations: try to match net force while staying in friction cones.
        for _ in range(3):
            achieved = np.sum(force_per_body[:, frame_idx, :], axis=0)
            delta = force_target - achieved
            if float(np.linalg.norm(delta)) < 1e-6:
                break
            for body_idx in active_indices:
                candidate = force_per_body[body_idx, frame_idx, :] + weights[body_idx] * delta
                force_per_body[body_idx, frame_idx, :] = _project_force_to_friction_cone(
                    force=candidate,
                    up=up,
                    friction_coeff=friction_coeff,
                )

    # Write a transparent per-frame debug CSV for inspection.
    with contact_wrench_csv_path.open("w", newline="", encoding="utf-8") as file_obj:
        writer = csv.writer(file_obj)
        header = [
            "frame",
            "time",
            "target_force_x",
            "target_force_y",
            "target_force_z",
            "achieved_force_x",
            "achieved_force_y",
            "achieved_force_z",
            "force_balance_residual_norm",
        ]
        for body_name in selected_names:
            header.extend(
                [
                    f"{body_name}_cop_x",
                    f"{body_name}_cop_y",
                    f"{body_name}_cop_z",
                    f"{body_name}_force_x",
                    f"{body_name}_force_y",
                    f"{body_name}_force_z",
                    f"{body_name}_moment_x",
                    f"{body_name}_moment_y",
                    f"{body_name}_moment_z",
                ]
            )
        writer.writerow(header)
        for frame_idx in range(frames):
            achieved = np.sum(force_per_body[:, frame_idx, :], axis=0)
            target = total_external_force[frame_idx, :]
            residual = float(np.linalg.norm(target - achieved))
            row: list[float | int] = [
                frame_idx,
                float(timestamps[frame_idx]),
                float(target[0]),
                float(target[1]),
                float(target[2]),
                float(achieved[0]),
                float(achieved[1]),
                float(achieved[2]),
                residual,
            ]
            for body_idx in range(len(selected_names)):
                row.extend(float(x) for x in cop_per_body[body_idx, frame_idx, :])
                row.extend(float(x) for x in force_per_body[body_idx, frame_idx, :])
                row.extend(float(x) for x in torque_per_body[body_idx, frame_idx, :])
            writer.writerow(row)

    # Create an OpenSim-compatible GRF MOT aligned with the generated ExternalLoads XML.
    labels = ["time"]
    for body_name in selected_names:
        labels.extend(
            [
                f"ground_force_{body_name}_vx",
                f"ground_force_{body_name}_vy",
                f"ground_force_{body_name}_vz",
                f"ground_force_{body_name}_px",
                f"ground_force_{body_name}_py",
                f"ground_force_{body_name}_pz",
                f"ground_force_{body_name}_mx",
                f"ground_force_{body_name}_my",
                f"ground_force_{body_name}_mz",
            ]
        )
    with grf_mot_path.open("w", encoding="utf-8") as file_obj:
        file_obj.write(f"name {trial_name}_grf_estimated\n")
        file_obj.write(f"datacolumns {len(labels)}\n")
        file_obj.write(f"datarows {frames}\n")
        file_obj.write(f"range {float(timestamps[0]):.8f} {float(timestamps[-1]):.8f}\n")
        file_obj.write("endheader\n")
        file_obj.write(" ".join(labels) + "\n")
        for frame_idx in range(frames):
            row = [float(timestamps[frame_idx])]
            for body_idx in range(len(selected_names)):
                row.extend(force_per_body[body_idx, frame_idx, :].tolist())
                row.extend(cop_per_body[body_idx, frame_idx, :].tolist())
                row.extend(torque_per_body[body_idx, frame_idx, :].tolist())
            file_obj.write(" ".join(f"{value:.8f}" for value in row) + "\n")

    nimble.biomechanics.OpenSimParser.saveOsimInverseDynamicsProcessedForcesXMLFile(
        trial_name,
        contact_nodes,
        grf_mot_path.name,
        str(external_loads_xml_path),
    )
    return grf_mot_path, external_loads_xml_path, contact_wrench_csv_path


def _infer_time_window_from_mot(ik_mot_path: Path) -> tuple[float, float]:
    labels, rows = parse_mot(ik_mot_path)
    lookup = {_canonical_label(label): idx for idx, label in enumerate(labels)}
    if "time" not in lookup:
        raise ValueError(f"Could not find 'time' column in IK motion: {ik_mot_path}")
    time_col = lookup["time"]
    start_time = float(rows[0][time_col])
    end_time = float(rows[-1][time_col])
    return start_time, end_time


def _resolve_id_column(dof_name: str, lookup: dict[str, int]) -> int | None:
    # OpenSim ID outputs moments for rotational coordinates and forces for translations.
    candidates = (
        dof_name,
        f"{dof_name}_moment",
        f"{dof_name}_force",
    )
    for candidate in candidates:
        if candidate in lookup:
            return lookup[candidate]
    return None


def run_inverse_dynamics_no_grf(
    model_path: str | Path,
    ik_mot_path: str | Path,
    output_dir: str | Path,
    trial_name: str,
    filter_mode: str = "auto",
    cutoff_hz: float | None = None,
) -> tuple[Path, Path, float | None]:
    """
    Run OpenSim inverse dynamics without explicit external loads.

    This computes generalized forces that reproduce the input kinematics under
    model dynamics and gravity, with no GRF/external wrench file provided.
    """
    try:
        import opensim
    except ImportError as exc:
        raise RuntimeError(
            "opensim Python package is required to compute inverse dynamics."
        ) from exc

    model_path = Path(model_path).resolve()
    ik_mot_path = Path(ik_mot_path).resolve()
    output_dir = Path(output_dir).resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    id_model_path = _prepare_model_for_inverse_dynamics(
        model_path=model_path,
        output_dir=output_dir,
        trial_name=trial_name,
    )
    start_time, end_time = _infer_time_window_from_mot(ik_mot_path)
    effective_cutoff = cutoff_hz
    if effective_cutoff is None:
        effective_cutoff = infer_cutoff_hz(filter_mode=filter_mode, mot_path=ik_mot_path)

    id_setup_path = output_dir / f"Setup_ID_noGRF_{trial_name}.xml"
    id_sto_path = output_dir / f"{trial_name}_id_noGRF.sto"

    opensim.Logger.setLevelString("error")
    id_tool = opensim.InverseDynamicsTool()
    id_tool.setName(f"{trial_name}_noGRF")
    id_tool.setModelFileName(str(id_model_path))
    id_tool.setCoordinatesFileName(str(ik_mot_path))
    id_tool.setStartTime(float(start_time))
    id_tool.setEndTime(float(end_time))
    if effective_cutoff is None:
        id_tool.setLowpassCutoffFrequency(-1.0)
    else:
        id_tool.setLowpassCutoffFrequency(float(effective_cutoff))
    id_tool.setResultsDir(str(output_dir))
    id_tool.setOutputGenForceFileName(id_sto_path.name)
    id_tool.printToXML(str(id_setup_path))

    _run_opensim_tool(id_setup_path)

    if not id_sto_path.exists():
        raise FileNotFoundError(f"Inverse dynamics output not found: {id_sto_path}")

    return id_setup_path, id_sto_path, effective_cutoff


def run_inverse_dynamics_with_estimated_grf(
    model_path: str | Path,
    ik_mot_path: str | Path,
    output_dir: str | Path,
    trial_name: str,
    filter_mode: str = "auto",
    cutoff_hz: float | None = None,
    contact_body_names: tuple[str, ...] = ("all",),
    friction_coeff: float = 0.8,
    contact_height_threshold_m: float = 0.06,
    contact_speed_threshold_mps: float = 0.6,
) -> tuple[Path, Path, float | None, Path, Path, Path]:
    """
    Run OpenSim ID using GRF/contact wrench estimated from kinematics.
    """
    try:
        import opensim
    except ImportError as exc:
        raise RuntimeError(
            "opensim Python package is required to compute inverse dynamics."
        ) from exc

    model_path = Path(model_path).resolve()
    ik_mot_path = Path(ik_mot_path).resolve()
    output_dir = Path(output_dir).resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    id_model_path = _prepare_model_for_inverse_dynamics(
        model_path=model_path,
        output_dir=output_dir,
        trial_name=trial_name,
    )
    start_time, end_time = _infer_time_window_from_mot(ik_mot_path)
    effective_cutoff = cutoff_hz
    if effective_cutoff is None:
        effective_cutoff = infer_cutoff_hz(filter_mode=filter_mode, mot_path=ik_mot_path)

    grf_mot_path, external_loads_xml_path, contact_wrench_csv_path = (
        _estimate_contact_wrenches_from_kinematics(
            model_path=id_model_path,
            ik_mot_path=ik_mot_path,
            output_dir=output_dir,
            trial_name=trial_name,
            contact_body_names=contact_body_names,
            friction_coeff=friction_coeff,
            contact_height_threshold_m=contact_height_threshold_m,
            contact_speed_threshold_mps=contact_speed_threshold_mps,
            force_cutoff_hz=effective_cutoff,
        )
    )

    id_setup_path = output_dir / f"Setup_ID_estimatedGRF_{trial_name}.xml"
    id_sto_path = output_dir / f"{trial_name}_id_estimatedGRF.sto"

    opensim.Logger.setLevelString("error")
    id_tool = opensim.InverseDynamicsTool()
    id_tool.setName(f"{trial_name}_estimatedGRF")
    id_tool.setModelFileName(str(id_model_path))
    id_tool.setCoordinatesFileName(str(ik_mot_path))
    id_tool.setExternalLoadsFileName(str(external_loads_xml_path))
    id_tool.setStartTime(float(start_time))
    id_tool.setEndTime(float(end_time))
    if effective_cutoff is None:
        id_tool.setLowpassCutoffFrequency(-1.0)
    else:
        id_tool.setLowpassCutoffFrequency(float(effective_cutoff))
    id_tool.setResultsDir(str(output_dir))
    id_tool.setOutputGenForceFileName(id_sto_path.name)
    id_tool.printToXML(str(id_setup_path))

    _run_opensim_tool(id_setup_path)
    if not id_sto_path.exists():
        raise FileNotFoundError(f"Inverse dynamics output not found: {id_sto_path}")

    return (
        id_setup_path,
        id_sto_path,
        effective_cutoff,
        grf_mot_path,
        external_loads_xml_path,
        contact_wrench_csv_path,
    )


def export_torque_csv_from_id_sto(
    id_sto_path: str | Path,
    model_path: str | Path,
    output_csv_path: str | Path,
    reference_times: np.ndarray | None = None,
) -> tuple[Path, int, tuple[str, ...], tuple[str, ...]]:
    """Export a DOF-ordered torque CSV from an ID .sto file."""
    id_sto_path = Path(id_sto_path).resolve()
    model_path = Path(model_path).resolve()
    output_csv_path = Path(output_csv_path).resolve()
    output_csv_path.parent.mkdir(parents=True, exist_ok=True)

    dof_names = extract_coordinate_names_from_osim(model_path)
    labels, rows = parse_mot(id_sto_path)
    lookup = {_canonical_label(label): idx for idx, label in enumerate(labels)}
    time_idx = lookup.get("time")
    if time_idx is None:
        raise ValueError(f"Could not find 'time' column in ID output: {id_sto_path}")
    id_times = np.asarray([float(row[time_idx]) for row in rows], dtype=float)
    if reference_times is None:
        target_times = id_times
    else:
        target_times = np.asarray(reference_times, dtype=float)

    missing: list[str] = []
    id_cols: list[int | None] = []
    for dof_name in dof_names:
        col_idx = _resolve_id_column(dof_name, lookup)
        if col_idx is None:
            missing.append(dof_name)
        id_cols.append(col_idx)

    torque_columns: list[np.ndarray] = []
    for col_idx in id_cols:
        if col_idx is None:
            torque_columns.append(np.full(target_times.shape, math.nan, dtype=float))
            continue
        id_values = np.asarray([float(row[col_idx]) for row in rows], dtype=float)
        if reference_times is None:
            torque_columns.append(id_values)
            continue
        # Align torque output to IK timestamps to keep kinematics and dynamics synchronized.
        torque_columns.append(
            np.interp(target_times, id_times, id_values, left=id_values[0], right=id_values[-1])
        )

    with output_csv_path.open("w", newline="", encoding="utf-8") as file_obj:
        writer = csv.writer(file_obj)
        header = ["frame", "time"]
        header.extend(f"{dof_name}_tau" for dof_name in dof_names)
        writer.writerow(header)

        for frame_idx in range(len(target_times)):
            out_row: list[float | int] = [frame_idx, float(target_times[frame_idx])]
            for values in torque_columns:
                out_row.append(float(values[frame_idx]))
            writer.writerow(out_row)

    return output_csv_path, len(target_times), tuple(dof_names), tuple(missing)


def run_inverse_dynamics_and_export_torque_csv(
    model_path: str | Path,
    ik_mot_path: str | Path,
    output_dir: str | Path,
    trial_name: str,
    torque_csv_path: str | Path,
    filter_mode: str = "auto",
    cutoff_hz: float | None = None,
    grf_mode: str = "estimated",
    contact_body_names: tuple[str, ...] = ("all",),
    friction_coeff: float = 0.8,
    contact_height_threshold_m: float = 0.06,
    contact_speed_threshold_mps: float = 0.6,
) -> InverseDynamicsNoGrfSummary:
    """High-level helper: run ID (no GRF) and export DOF torque CSV."""
    ik_labels, ik_rows = parse_mot(ik_mot_path)
    ik_lookup = {_canonical_label(label): idx for idx, label in enumerate(ik_labels)}
    ik_time_idx = ik_lookup.get("time")
    if ik_time_idx is None:
        raise ValueError(f"Could not find 'time' column in IK motion: {ik_mot_path}")
    reference_times = np.asarray([float(row[ik_time_idx]) for row in ik_rows], dtype=float)

    grf_mode_normalized = grf_mode.strip().lower()
    if grf_mode_normalized == "estimated":
        (
            id_setup_path,
            id_sto_path,
            effective_cutoff,
            grf_mot_path,
            external_loads_xml_path,
            contact_wrench_csv_path,
        ) = run_inverse_dynamics_with_estimated_grf(
            model_path=model_path,
            ik_mot_path=ik_mot_path,
            output_dir=output_dir,
            trial_name=trial_name,
            filter_mode=filter_mode,
            cutoff_hz=cutoff_hz,
            contact_body_names=contact_body_names,
            friction_coeff=friction_coeff,
            contact_height_threshold_m=contact_height_threshold_m,
            contact_speed_threshold_mps=contact_speed_threshold_mps,
        )
    elif grf_mode_normalized in ("none", "no_grf"):
        id_setup_path, id_sto_path, effective_cutoff = run_inverse_dynamics_no_grf(
            model_path=model_path,
            ik_mot_path=ik_mot_path,
            output_dir=output_dir,
            trial_name=trial_name,
            filter_mode=filter_mode,
            cutoff_hz=cutoff_hz,
        )
        grf_mot_path = None
        external_loads_xml_path = None
        contact_wrench_csv_path = None
    else:
        raise ValueError("Invalid grf_mode. Expected one of: estimated, none")

    torque_csv_path, frames, dof_names, missing_dofs = export_torque_csv_from_id_sto(
        id_sto_path=id_sto_path,
        model_path=model_path,
        output_csv_path=torque_csv_path,
        reference_times=reference_times,
    )
    return InverseDynamicsNoGrfSummary(
        model_path=Path(model_path).resolve(),
        ik_mot_path=Path(ik_mot_path).resolve(),
        id_setup_path=id_setup_path,
        id_sto_path=id_sto_path,
        torque_csv_path=torque_csv_path,
        dof_names=dof_names,
        frames=frames,
        cutoff_hz=effective_cutoff,
        missing_dofs=missing_dofs,
        grf_mode=grf_mode_normalized,
        grf_mot_path=grf_mot_path,
        external_loads_xml_path=external_loads_xml_path,
        contact_wrench_csv_path=contact_wrench_csv_path,
    )
