#!/usr/bin/env python3
from __future__ import annotations

import argparse
import csv
import math
import shutil
import time
from pathlib import Path
from xml.etree import ElementTree as ET

import numpy as np


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Load an OpenSim model in nimblephysics and replay positions from a "
            "pipeline CSV (<dof>, <dof>_vel, <dof>_acc)."
        )
    )
    parser.add_argument(
        "--osim",
        default="model/LaiUhlrich2022_torque_only.osim",
        help="Path to .osim model file",
    )
    parser.add_argument(
        "--csv",
        default="outputs/OpenSim/IK/demo_torque/demo_torque_dofs.csv",
        help="Path to DOF CSV generated by run_amass_to_opensim.py",
    )
    parser.add_argument(
        "--geometry-dir",
        default=None,
        help="Path to Geometry directory (used only with --load-geometry)",
    )
    parser.add_argument(
        "--load-geometry",
        dest="load_geometry",
        action="store_true",
        help="Load geometry meshes from disk (default: enabled).",
    )
    parser.add_argument(
        "--no-load-geometry",
        dest="load_geometry",
        action="store_false",
        help="Disable geometry loading.",
    )
    parser.add_argument(
        "--max-frames",
        type=int,
        default=None,
        help="Optional max number of frames to replay",
    )
    parser.add_argument(
        "--realtime",
        dest="realtime",
        action="store_true",
        help="Run replay in realtime using the CSV time column (default: enabled).",
    )
    parser.add_argument(
        "--no-realtime",
        dest="realtime",
        action="store_false",
        help="Disable realtime pacing and run as fast as possible.",
    )
    parser.add_argument(
        "--speed",
        type=float,
        default=1.0,
        help="Realtime playback speed multiplier (default: 1.0)",
    )
    parser.add_argument(
        "--port",
        type=int,
        default=8080,
        help="HTTP port for the Nimble GUI server (default: 8080).",
    )
    parser.add_argument(
        "--keep-gui-open",
        dest="keep_gui_open",
        action="store_true",
        help="Keep GUI open after replay.",
    )
    parser.add_argument(
        "--no-keep-gui-open",
        dest="keep_gui_open",
        action="store_false",
        help="Close GUI automatically after replay.",
    )
    parser.add_argument(
        "--start-delay-seconds",
        type=float,
        default=3.0,
        help="Delay before replay starts, so you can open the GUI link (default: 3.0).",
    )
    parser.set_defaults(realtime=True, keep_gui_open=False, load_geometry=True)
    return parser.parse_args()


def _is_translational_dof(dof_name: str) -> bool:
    # OpenSim translational DOFs usually end with _tx/_ty/_tz.
    return dof_name.endswith("_tx") or dof_name.endswith("_ty") or dof_name.endswith("_tz")


def _load_csv_rows(csv_path: Path) -> tuple[list[dict[str, str]], bool]:
    with csv_path.open("r", encoding="utf-8") as file_obj:
        reader = csv.DictReader(file_obj)
        rows = list(reader)
        if not rows:
            raise ValueError(f"CSV has no data rows: {csv_path}")
        has_time = "time" in reader.fieldnames if reader.fieldnames else False
    return rows, bool(has_time)


def _to_float(value: str, column_name: str, row_idx: int) -> float:
    try:
        return float(value)
    except Exception as exc:  # noqa: BLE001
        raise ValueError(
            f"Invalid numeric value at row {row_idx + 1}, column '{column_name}': {value}"
        ) from exc


def _build_positions(
    rows: list[dict[str, str]],
    dof_names: list[str],
    default_q: np.ndarray,
) -> tuple[np.ndarray, np.ndarray | None]:
    n_frames = len(rows)
    n_dofs = len(dof_names)
    q_matrix = np.tile(default_q.reshape(1, n_dofs), (n_frames, 1))

    has_time = "time" in rows[0]
    time_values: np.ndarray | None = np.zeros(n_frames, dtype=np.float64) if has_time else None

    available_dofs = [name for name in dof_names if name in rows[0]]
    missing_dofs = [name for name in dof_names if name not in rows[0]]
    missing_non_lock = [name for name in missing_dofs if not name.endswith("_lock")]
    if missing_non_lock:
        print(
            "Warning: some model DOFs are not present in CSV and will keep default value: "
            + ", ".join(missing_non_lock)
        )

    for frame_idx, row in enumerate(rows):
        if has_time and time_values is not None:
            time_values[frame_idx] = _to_float(row["time"], "time", frame_idx)
        for dof_idx, dof_name in enumerate(dof_names):
            if dof_name not in row:
                continue
            value = _to_float(row[dof_name], dof_name, frame_idx)
            # CSV positions use OpenSim units: rotational in degrees, translational in meters.
            # Nimble expects radians for rotational coordinates.
            if not _is_translational_dof(dof_name):
                value = value * math.pi / 180.0
            q_matrix[frame_idx, dof_idx] = value

    if not available_dofs:
        raise ValueError(
            "No model DOF columns found in CSV. Expected columns named like the model DOFs."
        )
    return q_matrix, time_values


def _resolve_geometry_dir(osim_path: Path, explicit_geometry_dir: str | None) -> Path | None:
    """Resolve Geometry dir with robust fallbacks."""
    candidates: list[Path] = []
    if explicit_geometry_dir:
        candidates.append(Path(explicit_geometry_dir).resolve())
    candidates.append((osim_path.parent / "Geometry").resolve())
    repo_root = Path(__file__).resolve().parents[1]
    candidates.append((repo_root / "model" / "Geometry").resolve())

    seen: set[str] = set()
    for candidate in candidates:
        key = str(candidate)
        if key in seen:
            continue
        seen.add(key)
        if candidate.exists() and candidate.is_dir():
            return candidate
    return None


def _mesh_files_from_osim(osim_path: Path) -> list[str]:
    try:
        root = ET.parse(osim_path).getroot()
    except ET.ParseError:
        return []
    mesh_files: list[str] = []
    for node in root.findall(".//mesh_file"):
        if node.text is None:
            continue
        text = node.text.strip()
        if text:
            mesh_files.append(text)
    return mesh_files


def _geometry_is_nimble_compatible(osim_path: Path, geometry_dir: Path) -> tuple[bool, list[str]]:
    """
    Nimble often looks for `<mesh_file>.ply` sidecars.
    If they are missing, geometry loading generates a long list of warnings.
    """
    mesh_files = _mesh_files_from_osim(osim_path)
    if not mesh_files:
        return True, []
    missing_sidecars: list[str] = []
    for mesh in mesh_files:
        sidecar = geometry_dir / f"{mesh}.ply"
        if not sidecar.exists():
            missing_sidecars.append(sidecar.name)
    # Consider compatible only if all sidecars are present.
    return len(missing_sidecars) == 0, missing_sidecars


def _safe_link_or_copy(src: Path, dst: Path) -> None:
    dst.parent.mkdir(parents=True, exist_ok=True)
    if dst.exists():
        return
    try:
        dst.symlink_to(src)
    except Exception:  # noqa: BLE001
        shutil.copy2(src, dst)


def _prepare_nimble_sidecars(
    osim_path: Path,
    geometry_dir: Path,
) -> tuple[int, list[str]]:
    """
    Nimble resolves meshes as `<osim_dir>/<mesh_file>.ply`.
    This helper materializes missing sidecars next to the .osim.
    """
    mesh_files = _mesh_files_from_osim(osim_path)
    created = 0
    unresolved: list[str] = []
    model_dir = osim_path.parent

    meshio_module = None

    for mesh in mesh_files:
        target = model_dir / f"{mesh}.ply"
        if target.exists():
            continue

        candidate_ply = geometry_dir / f"{mesh}.ply"
        candidate_raw = geometry_dir / mesh

        if candidate_ply.exists():
            _safe_link_or_copy(candidate_ply, target)
            created += 1
            continue

        if not candidate_raw.exists():
            unresolved.append(mesh)
            continue

        # If source is already a .ply, link/copy directly.
        if candidate_raw.suffix.lower() == ".ply":
            _safe_link_or_copy(candidate_raw, target)
            created += 1
            continue

        # Convert VTP -> PLY when needed.
        if candidate_raw.suffix.lower() == ".vtp":
            if meshio_module is None:
                try:
                    import meshio as _meshio
                    meshio_module = _meshio
                except Exception:  # noqa: BLE001
                    meshio_module = False

            if meshio_module:
                try:
                    mesh_data = meshio_module.read(candidate_raw)
                    meshio_module.write(target, mesh_data, file_format="ply")
                    created += 1
                    continue
                except Exception:  # noqa: BLE001
                    unresolved.append(mesh)
                    continue

        unresolved.append(mesh)

    return created, unresolved


def main() -> int:
    args = parse_args()

    try:
        import nimblephysics as nimble
    except ImportError as exc:
        raise SystemExit(
            "nimblephysics is not installed in this Python environment. "
            "Install it and rerun this script."
        ) from exc

    gui = nimble.NimbleGUI()
    try:
        gui.serve(int(args.port))
    except OSError as exc:
        raise SystemExit(
            f"Failed to start GUI on http://localhost:{args.port} "
            f"(port may be in use): {exc}"
        ) from exc
    # Keep an explicit reference to the GUI server object.
    websocket_server = gui.guiServer

    osim_path = Path(args.osim).resolve()
    if not osim_path.exists():
        raise SystemExit(f"Model file not found: {osim_path}")

    csv_path = Path(args.csv).resolve()
    if not csv_path.exists():
        raise SystemExit(f"CSV file not found: {csv_path}")

    if bool(args.load_geometry):
        geometry_dir = _resolve_geometry_dir(osim_path, args.geometry_dir)
        if geometry_dir is None:
            print(
                "Warning: no valid Geometry directory found. "
                "Falling back to ignoreGeometry=True."
            )
            geometry_dir = None
            geometry_dir_str = ""
            ignore_geometry = True
        else:
            created_sidecars, unresolved_sidecars = _prepare_nimble_sidecars(
                osim_path=osim_path,
                geometry_dir=geometry_dir,
            )
            if created_sidecars > 0:
                print(
                    f"Prepared {created_sidecars} Nimble mesh sidecars next to the model."
                )
            is_compatible, missing_sidecars = _geometry_is_nimble_compatible(
                osim_path=osim_path,
                geometry_dir=geometry_dir,
            )
            if not is_compatible:
                if unresolved_sidecars:
                    print(
                        "Warning: could not create all required geometry sidecars "
                        f"(first 10: {', '.join(unresolved_sidecars[:10])}). "
                        "Falling back to ignoreGeometry=True."
                    )
                    geometry_dir = None
                    geometry_dir_str = ""
                    ignore_geometry = True
                else:
                    # Sidecars might have been prepared in model dir, allow loading anyway.
                    geometry_dir_str = str(geometry_dir)
                    ignore_geometry = False
                    print(f"Using Geometry dir: {geometry_dir}")
            else:
                geometry_dir_str = str(geometry_dir)
                ignore_geometry = False
                print(f"Using Geometry dir: {geometry_dir}")
    else:
        geometry_dir = None
        geometry_dir_str = ""
        ignore_geometry = True

    opensim_file: nimble.biomechanics.OpenSimFile = nimble.biomechanics.OpenSimParser.parseOsim(
        str(osim_path),
        geometry_dir_str,
        bool(ignore_geometry),
    )
    skeleton: nimble.dynamics.Skeleton = opensim_file.skeleton
    dof_names = [skeleton.getDofByIndex(i).getName() for i in range(skeleton.getNumDofs())]
    default_q = np.asarray(skeleton.getPositions(), dtype=np.float64)

    rows, has_time = _load_csv_rows(csv_path)
    q_matrix, time_values = _build_positions(rows, dof_names, default_q)

    if args.max_frames is not None and args.max_frames > 0:
        q_matrix = q_matrix[: args.max_frames]
        if time_values is not None:
            time_values = time_values[: args.max_frames]

    try:
        start_delay = max(0.0, float(args.start_delay_seconds))
        if start_delay > 0:
            print(
                f"GUI available on http://localhost:{args.port}. "
                f"Starting replay in {start_delay:.1f}s..."
            )
            time.sleep(start_delay)

        for frame_idx in range(q_matrix.shape[0]):
            skeleton.setPositions(q_matrix[frame_idx, :])
            gui.nativeAPI().renderSkeleton(skeleton)

            if bool(args.realtime):
                if has_time and time_values is not None and frame_idx > 0:
                    dt = max(0.0, float(time_values[frame_idx] - time_values[frame_idx - 1]))
                else:
                    # Fallback to ~120Hz if no time column is available.
                    dt = 1.0 / 120.0
                speed = max(1e-6, float(args.speed))
                time.sleep(dt / speed)

        print(f"Loaded model: {osim_path}")
        print(f"Loaded CSV: {csv_path}")
        print(f"Load geometry: {not bool(ignore_geometry)}")
        if not bool(ignore_geometry) and geometry_dir is not None:
            print(f"Geometry dir: {geometry_dir}")
        print(f"Replayed frames: {q_matrix.shape[0]}")
        print(f"Model DOFs: {len(dof_names)}")

        if bool(args.keep_gui_open):
            print(f"GUI is running on http://localhost:{args.port}. Press Ctrl+C to close.")
            while True:
                time.sleep(0.25)
    finally:
        # Avoid Nimble warning/error on server deallocation.
        if hasattr(gui, "stopServing"):
            gui.stopServing()
        elif websocket_server is not None and hasattr(websocket_server, "stopServing"):
            websocket_server.stopServing()

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
